### PR TITLE
delete footer transparenncy link

### PR DESCRIPTION
**Pull request by tomobre**

### CODE REVIEW

**Review by Bilb — APPROVED** [review]

**Comment by majestrate** [comment]
On Sun, 15 Jan 2023 15:48:31 -0800
Tomas Obregon ***@***.***> wrote:

> Merged #25 into main.
> 

can we get a rundown on why we merged this?

thanks.

**Comment by KeeJef** [comment]
Yeah can we revert this, no reason why it should have been removed, since the link hits the website correctly here https://optf.ngo/transparency/

**Comment by majestrate** [comment]
On Mon, 16 Jan 2023 23:09:21 -0800
Kee Jefferys ***@***.***> wrote:

> Yeah can we revert this, no reason why it should have been removed,
> since the link hits the website correctly here
> https://optf.ngo/transparency/
> 

internal misunderstanding then?

**Comment by KeeJef** [comment]
> On Mon, 16 Jan 2023 23:09:21 -0800 Kee Jefferys ***@***.***> wrote: Yeah can we revert this, no reason why it should have been removed, since the link hits the website correctly here https://optf.ngo/transparency/
> internal misunderstanding then?

Yes

**Comment by KeeJef** [comment]
This commit has been reverted here https://github.com/oxen-io/session-website/pull/26, the transparency report has been updated and restored on the OPTF website https://optf.ngo/transparency/

**Pull request merged**
